refactors confirmdeletemodal component
uclaacm/TeachLAFrontend pull request #524
Opened 2021-05-19 07:09 UTC by ldalton02

2021-05-19 20:26 UTC, reginawang99 requested changes
looks mostly good to me! much speed 🚗 🔥 

one tiny thing: lets extract the props! it makes it easier to see what we props are actually being used

2021-05-19 20:26 UTC, reginawang99 commented on src/components/Sketches/components/ConfirmDeleteModal.js
> +import { programUploadSuccess } from 'actions/userDataActions.js';
nit: can we remove this line if we aren't using the import?

2021-05-19 22:47 UTC, reginawang99 commented
last thing! Could u add in closes #493 in the description?

2021-05-19 22:52 UTC, reginawang99 approved these changes
Looks good to me!! 🥳🎉 congrats on first react pull request :)) exciting times hehe

@lumisphere902 any thoughts?

2021-05-20 00:01 UTC, lumisphere902 approved these changes
LGTM. Now that I'm looking at it though... neither of the state variable are actually used lol. I think error can be removed, but spinner could be pretty easily implemented. What do you think?

2021-05-20 05:47 UTC, reginawang99 commented
hm i dont know editor super well, but i would just leave it in, cuz it doesn't really hurt anything. 

I'm not sure if y'all's were planning on using it in the future or anything? You probably know best

2021-05-20 21:42 UTC, merged