Update ConfirmLeaveModal.js
uclaacm/TeachLAFrontend pull request #707
Opened 2021-11-09 20:23 UTC by Nhamakami7

I'm not completely sure if my changes from class to functional were correct. Could I have my work checked over?

2021-11-09 21:19 UTC, lumisphere902 requested changes
Mostly good, just a couple of small issues. Also, you should merge in the latest master and fix all the lint issues. Let me know if you need help with that!

2021-11-09 21:19 UTC, lumisphere902 commented on src/components/Classes/components/ConfirmLeaveModal.js
> +  const [error, setError] = useState("");
You need to import `useState` to use it here. For example, `import React, { useState } from "react";`

2021-11-09 21:19 UTC, lumisphere902 commented on src/components/Classes/components/ConfirmLeaveModal.js
> +  /*
You can just delete this instead of commenting it out.

2021-11-09 23:21 UTC, reginawang3495 commented
I'd recommend testing this out!! This probably wouldn't have compiled :)

2021-12-29 19:01 UTC, reginawang3495 requested changes
just some removals :)

2021-12-29 19:01 UTC, reginawang3495 commented on src/components/Classes/components/ConfirmLeaveModal.js
> +            // });
remove?

2021-12-29 19:01 UTC, reginawang3495 commented on src/components/Classes/components/ConfirmLeaveModal.js
> +          // props.inClass ? props.unsetClass() : closeModal();
remove?

2021-12-29 19:12 UTC, reginawang3495 approved these changes
small nits then feel free to merge!

2021-12-29 21:22 UTC, merged