refactoring
uclaacm/TeachLAFrontend pull request #708
Opened 2021-11-10 00:54 UTC by remasbashanfar

2021-11-10 07:08 UTC, lumisphere902 requested changes
The refactor looks to be mostly correct, but there are a number of lint errors. Most should be fixed automatically; let me know if you have any issues with fixing them!

2021-11-10 22:36 UTC, reginawang3495 commented
hai hai i dont think you tested this manually right? if you did then these issues wouldn't be here! lmk if you need help figuring out how to run this :)

2021-11-17 06:10 UTC, nendow02 requested changes
Looks good! Just have a few small suggestions.

2021-11-17 06:10 UTC, nendow02 commented on src/components/TextEditor/components/ShareSketchModal.js
> - * @param {String} shareUrl the URL to display/copy to clipboard
We don’t have to change the comments

2021-11-17 06:10 UTC, nendow02 commented on src/components/TextEditor/components/ShareSketchModal.js
> +  const [str, setStr] = useState([{ copyStatus: 'Hit "Copy to Clipboard"!' }]);
Can we instead make this useState called 'copyStatus' and 'setCopyStatus' that stores a string.  You may have to also change the lines that call this later on.

2021-11-17 08:09 UTC, lumisphere902 commented
LGTM once @nendow02's comments have been addressed. :)

2022-01-23 06:03 UTC, reginawang3495 commented
@remasbashanfar Would you like to resolve conflicts and then we can merge in? Thanks!

2022-05-04 23:40 UTC, lumisphere902 commented
This has been around for a while, just cleaned it up @nendow02

2022-05-06 06:04 UTC, nendow02 approved these changes

2022-05-06 08:11 UTC, lumisphere902 approved these changes

2022-05-06 08:11 UTC, merged